name: UnaMentis
options:
  bundleIdPrefix: com.unamentis
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "15.2"
  minimumXcodeGenVersion: "2.40"
  createIntermediateGroups: true
  generateEmptyDirectories: true
  groupSortPosition: top
  usesTabs: false
  indentWidth: 4

settings:
  base:
    SWIFT_VERSION: "6.0"
    TARGETED_DEVICE_FAMILY: "1"  # iPhone only
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    DEVELOPMENT_TEAM: ""
  configs:
    Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    Release:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: ""

packages:
  LiveKit:
    url: https://github.com/livekit/client-sdk-swift.git
    from: "2.0.0"
  SwiftLog:
    url: https://github.com/apple/swift-log.git
    from: "1.5.0"
  Collections:
    url: https://github.com/apple/swift-collections.git
    from: "1.1.0"
  # LlamaCpp SPM package removed - use local llama.xcframework for on-device LLM
  # See docs/plan for xcframework setup instructions

targets:
  UnaMentis:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: UnaMentis
        excludes:
          - "**/.DS_Store"
          # ManagedObjects included now - using manual classes with no auto-generation
          - "**/SelfHostedSTTService.swift"  # Has duplicate STTMetrics/STTError types
          - "**/OnDeviceLLMService.swift"  # Uses incompatible llama.cpp API, use SelfHostedLLMService instead
      - path: models/llama-3.2-3b-instruct-q4_k_m.gguf
        buildPhase: resources
        type: file
    dependencies:
      - package: LiveKit
      - package: SwiftLog
        product: Logging
      - package: Collections
      # LlamaCpp dependency removed - using server-hosted LLM via SelfHostedLLMService
    settings:
      base:
        INFOPLIST_FILE: UnaMentis/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.unamentis.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: YES
        GENERATE_INFOPLIST_FILE: NO
    info:
      path: UnaMentis/Info.plist
      properties:
        CFBundleName: UnaMentis
        CFBundleDisplayName: UnaMentis
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: UnaMentis
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities:
          - arm64
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSMicrophoneUsageDescription: "UnaMentis needs microphone access for voice-based educational conversations."
        NSSpeechRecognitionUsageDescription: "UnaMentis uses speech recognition for voice commands."
        UIBackgroundModes:
          - audio
        BGTaskSchedulerPermittedIdentifiers:
          - com.unamentis.session-sync
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
    entitlements:
      path: UnaMentis/UnaMentis.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.device.audio-input: true
        com.apple.security.network.client: true

  UnaMentisTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: UnaMentisTests
        excludes:
          - "**/.DS_Store"
          - E2E  # E2E tests separate
    dependencies:
      - target: UnaMentis
    settings:
      base:
        INFOPLIST_FILE: UnaMentisTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.unamentis.tests
        GENERATE_INFOPLIST_FILE: YES

schemes:
  UnaMentis:
    build:
      targets:
        UnaMentis: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - name: UnaMentisTests
          parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
