name: UnaMentis
options:
  bundleIdPrefix: com.unamentis
  deploymentTarget:
    iOS: "18.0"
    watchOS: "26.0"
  xcodeVersion: "15.2"
  minimumXcodeGenVersion: "2.40"
  createIntermediateGroups: true
  generateEmptyDirectories: true
  groupSortPosition: top
  usesTabs: false
  indentWidth: 4

settings:
  base:
    SWIFT_VERSION: "6.0"
    TARGETED_DEVICE_FAMILY: "1"  # iPhone only
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    DEVELOPMENT_TEAM: ""
  configs:
    Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    Release:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: ""

packages:
  LiveKit:
    url: https://github.com/livekit/client-sdk-swift.git
    from: "2.0.0"
  SwiftLog:
    url: https://github.com/apple/swift-log.git
    from: "1.5.0"
  Collections:
    url: https://github.com/apple/swift-collections.git
    from: "1.1.0"
  # LlamaCpp SPM package removed - use local llama.xcframework for on-device LLM
  # See docs/plan for xcframework setup instructions

targets:
  UnaMentis:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: UnaMentis
        excludes:
          - "**/.DS_Store"
          - "**/*.md"  # Exclude all markdown documentation files
          - "**/Testing/LatencyHarness/TestHooks.swift"  # Has duplicate provider extensions
          # ManagedObjects included now - using manual classes with no auto-generation
          - "**/SelfHostedSTTService.swift"  # Has duplicate STTMetrics/STTError types
          - "**/OnDeviceLLMService.swift"  # Uses incompatible llama.cpp API, use SelfHostedLLMService instead
          # Kyutai/PocketTTS subsystem - xcframework not linked, use SelfHostedTTSService
          - "**/KyutaiPocketTTSService.swift"
          - "**/KyutaiPocketTTSConfig.swift"
          - "**/PocketTTSBindings.swift"
          - "**/KyutaiPocketModelManager.swift"
          - "**/KyutaiPocketSettingsView.swift"
          - "**/KyutaiPocketSettingsViewModel.swift"
          # Modules/KnowledgeBowl - exclude entire substructure, keep only KnowledgeBowlModule.swift
          # The module facade references Core/ and UI/ versions for actual implementation
          - "Modules/KnowledgeBowl/Models/**"    # Duplicates of Core/KnowledgeBowl/
          - "Modules/KnowledgeBowl/Views/**"     # Duplicates of UI/KnowledgeBowl/
          - "Modules/KnowledgeBowl/Services/**"  # Duplicates of Services/KnowledgeBowl/
          - "Modules/KnowledgeBowl/Engine/**"    # Duplicates of Services/KnowledgeBowl/
      - path: Shared
        excludes:
          - "**/.DS_Store"
      - path: models/llama-3.2-3b-instruct-q4_k_m.gguf
        buildPhase: resources
        type: file
      - path: UnaMentis/Resources/kb-sample-questions.json
        buildPhase: resources
        type: file
    dependencies:
      - target: UnaMentis Watch App
        embed: true
      - package: LiveKit
      - package: SwiftLog
        product: Logging
      - package: Collections
      # LlamaCpp dependency removed - using server-hosted LLM via SelfHostedLLMService
    settings:
      base:
        INFOPLIST_FILE: UnaMentis/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.unamentis.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: YES
        GENERATE_INFOPLIST_FILE: NO
    info:
      path: UnaMentis/Info.plist
      properties:
        CFBundleName: UnaMentis
        CFBundleDisplayName: UnaMentis
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: UnaMentis
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities:
          - arm64
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSMicrophoneUsageDescription: "UnaMentis needs microphone access for voice-based educational conversations."
        NSSpeechRecognitionUsageDescription: "UnaMentis uses speech recognition for voice commands."
        UIBackgroundModes:
          - audio
        BGTaskSchedulerPermittedIdentifiers:
          - com.unamentis.session-sync
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
    entitlements:
      path: UnaMentis/UnaMentis.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.device.audio-input: true
        com.apple.security.network.client: true

  UnaMentisTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: UnaMentisTests
        excludes:
          - "**/.DS_Store"
          - E2E  # E2E tests separate
          # Tests for excluded Modules classes
          - "Unit/KnowledgeBowl/KBStatsManagerTests.swift"
          - "Unit/KnowledgeBowl/KBPracticeEngineTests.swift"
          # Tests with stale API signatures (need maintenance)
          - "Unit/KnowledgeBowl/KBOnDeviceSTTTests.swift"
          - "Unit/KnowledgeBowl/KBOnDeviceTTSTests.swift"
          - "Unit/KnowledgeBowl/KBQuestionTests.swift"
          - "Unit/KnowledgeBowl/KBQuestionEngineTests.swift"
          - "Unit/KnowledgeBowl/KBTransformerTests.swift"
          - "Unit/KnowledgeBowl/KBAnswerValidatorTests.swift"  # validate() now async
          - "Unit/KnowledgeBowl/KBReboundSimulatorTests.swift"  # stale KBQuestion API
          - "Unit/KnowledgeBowl/KBRegionalConfigTests.swift"  # stale KBQuestion/KBDifficulty API
          - "Unit/KnowledgeBowl/KBMatchEngineTests.swift"  # stale KBQuestion API, actor isolation
          - "Unit/KnowledgeBowl/Validation/KBNGramMatcherTests.swift"  # stale pronunciation parameter
          - "Unit/KnowledgeBowl/Validation/KBPhoneticMatcherTests.swift"  # stale pronunciation parameter
          - "Unit/Services/GLMASRSTTServiceTests.swift"  # async API changes
          - "Integration/GLMASRIntegrationTests.swift"  # async API changes
          - "Integration/KnowledgeBowl/KBAnswerValidationIntegrationTests.swift"  # async API changes
          - "Integration/KnowledgeBowl/KBSessionIntegrationTests.swift"  # stale KBQuestion API
      # Note: Shared is inherited from UnaMentis target dependency, don't include separately
    dependencies:
      - target: UnaMentis
    settings:
      base:
        INFOPLIST_FILE: UnaMentisTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.unamentis.tests
        GENERATE_INFOPLIST_FILE: YES

  UnaMentis Watch App:
    type: application
    platform: watchOS
    deploymentTarget: "26.0"
    sources:
      - path: UnaMentis Watch App
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: UnaMentis Watch App/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.unamentis.app.watchkitapp
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: YES
        GENERATE_INFOPLIST_FILE: NO
        TARGETED_DEVICE_FAMILY: "4"
    info:
      path: UnaMentis Watch App/Info.plist
      properties:
        CFBundleName: UnaMentis Watch App
        CFBundleDisplayName: UnaMentis
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        CFBundlePackageType: APPL
        WKCompanionAppBundleIdentifier: com.unamentis.app
        WKRunsIndependentlyOfCompanionApp: false
        WKApplication: true
        UIDeviceFamily:
          - 4

schemes:
  UnaMentis:
    build:
      targets:
        UnaMentis: all
        UnaMentis Watch App: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - name: UnaMentisTests
          parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  UnaMentis Watch App:
    build:
      targets:
        UnaMentis Watch App: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
