// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(pocket_tts_iosFFI)
    import pocket_tts_iosFFI
#endif

private extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len: 0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_pocket_tts_ios_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_pocket_tts_ios_rustbuffer_free(self, $0) }
    }
}

private extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

private extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

private func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
private func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset ..< reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value) { reader.data.copyBytes(to: $0, from: range) }
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
private func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> [UInt8] {
    let range = reader.offset ..< (reader.offset + count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer { buffer in
        reader.data.copyBytes(to: buffer, from: range)
    }
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
private func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return try Float(bitPattern: readInt(&reader))
}

// Reads a float at the current offset.
private func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return try Double(bitPattern: readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
private func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

private func createWriter() -> [UInt8] {
    return []
}

private func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
private func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

private func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

private func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
private protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
private protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType {}

extension FfiConverterPrimitive {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
private protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
        var writer = createWriter()
        write(value, into: &writer)
        return RustBuffer(bytes: writer)
    }
}

// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
private enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

private extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        lock()
        defer { self.unlock() }
        return try f()
    }
}

private let CALL_SUCCESS: Int8 = 0
private let CALL_ERROR: Int8 = 1
private let CALL_UNEXPECTED_ERROR: Int8 = 2
private let CALL_CANCELLED: Int8 = 3

private extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T
) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
    case CALL_SUCCESS:
        return

    case CALL_ERROR:
        if let errorHandler = errorHandler {
            throw try errorHandler(callStatus.errorBuf)
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.unexpectedRustCallError
        }

    case CALL_UNEXPECTED_ERROR:
        // When the rust code sees a panic, it tries to construct a RustBuffer
        // with the message.  But if that code panics, then it just sends back
        // an empty buffer.
        if callStatus.errorBuf.len > 0 {
            throw try UniffiInternalError.rustPanic(FfiConverterString.lift(callStatus.errorBuf))
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.rustPanic("Rust panic")
        }

    case CALL_CANCELLED:
        fatalError("Cancellation not supported yet")

    default:
        throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void
) {
    do {
        try writeReturn(makeCall())
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void,
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

    func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        map.count
    }
}

// Public interface members begin here.

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterBool: FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return try String(bytes: readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return try Data(readBytes(&buf, count: Int(len)))
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}

public protocol PocketTtsEngineProtocol: AnyObject {
    func cancel()

    func clearReferenceAudio()

    func configure(config: TtsConfig) throws

    func decodeLatents(latentsData: Data, numFrames: UInt32) throws -> SynthesisResult

    func getConfig() -> TtsConfig

    func isReady() -> Bool

    func modelVersion() -> String

    func parameterCount() -> UInt64

    func setReferenceAudio(audioData: Data, sampleRate: UInt32) throws

    func startTrueStreaming(text: String, handler: TtsEventHandler) throws

    func synthesize(text: String) throws -> SynthesisResult

    func synthesizeWithVoice(text: String, voiceIndex: UInt32) throws -> SynthesisResult

    func unload()
}

open class PocketTtsEngine:
    PocketTtsEngineProtocol
{
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    public required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noPointer _: NoPointer) {
        pointer = nil
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_pocket_tts_ios_fn_clone_pocketttsengine(self.pointer, $0) }
    }

    public convenience init(modelPath: String) throws {
        let pointer =
            try rustCallWithError(FfiConverterTypePocketTTSError.lift) {
                uniffi_pocket_tts_ios_fn_constructor_pocketttsengine_new(
                    FfiConverterString.lower(modelPath), $0
                )
            }
        self.init(unsafeFromRawPointer: pointer)
    }

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_pocket_tts_ios_fn_free_pocketttsengine(pointer, $0) }
    }

    open func cancel() { try! rustCall {
        uniffi_pocket_tts_ios_fn_method_pocketttsengine_cancel(self.uniffiClonePointer(), $0)
    }
    }

    open func clearReferenceAudio() { try! rustCall {
        uniffi_pocket_tts_ios_fn_method_pocketttsengine_clear_reference_audio(self.uniffiClonePointer(), $0)
    }
    }

    open func configure(config: TtsConfig) throws { try rustCallWithError(FfiConverterTypePocketTTSError.lift) {
        uniffi_pocket_tts_ios_fn_method_pocketttsengine_configure(self.uniffiClonePointer(),
                                                                  FfiConverterTypeTTSConfig.lower(config), $0)
    }
    }

    open func decodeLatents(latentsData: Data, numFrames: UInt32) throws -> SynthesisResult {
        return try FfiConverterTypeSynthesisResult.lift(rustCallWithError(FfiConverterTypePocketTTSError.lift) {
            uniffi_pocket_tts_ios_fn_method_pocketttsengine_decode_latents(self.uniffiClonePointer(),
                                                                           FfiConverterData.lower(latentsData),
                                                                           FfiConverterUInt32.lower(numFrames), $0)
        })
    }

    open func getConfig() -> TtsConfig {
        return try! FfiConverterTypeTTSConfig.lift(try! rustCall {
            uniffi_pocket_tts_ios_fn_method_pocketttsengine_get_config(self.uniffiClonePointer(), $0)
        })
    }

    open func isReady() -> Bool {
        return try! FfiConverterBool.lift(try! rustCall {
            uniffi_pocket_tts_ios_fn_method_pocketttsengine_is_ready(self.uniffiClonePointer(), $0)
        })
    }

    open func modelVersion() -> String {
        return try! FfiConverterString.lift(try! rustCall {
            uniffi_pocket_tts_ios_fn_method_pocketttsengine_model_version(self.uniffiClonePointer(), $0)
        })
    }

    open func parameterCount() -> UInt64 {
        return try! FfiConverterUInt64.lift(try! rustCall {
            uniffi_pocket_tts_ios_fn_method_pocketttsengine_parameter_count(self.uniffiClonePointer(), $0)
        })
    }

    open func setReferenceAudio(audioData: Data, sampleRate: UInt32) throws { try rustCallWithError(FfiConverterTypePocketTTSError.lift) {
        uniffi_pocket_tts_ios_fn_method_pocketttsengine_set_reference_audio(self.uniffiClonePointer(),
                                                                            FfiConverterData.lower(audioData),
                                                                            FfiConverterUInt32.lower(sampleRate), $0)
    }
    }

    open func startTrueStreaming(text: String, handler: TtsEventHandler) throws { try rustCallWithError(FfiConverterTypePocketTTSError.lift) {
        uniffi_pocket_tts_ios_fn_method_pocketttsengine_start_true_streaming(self.uniffiClonePointer(),
                                                                             FfiConverterString.lower(text),
                                                                             FfiConverterCallbackInterfaceTtsEventHandler.lower(handler), $0)
    }
    }

    open func synthesize(text: String) throws -> SynthesisResult {
        return try FfiConverterTypeSynthesisResult.lift(rustCallWithError(FfiConverterTypePocketTTSError.lift) {
            uniffi_pocket_tts_ios_fn_method_pocketttsengine_synthesize(self.uniffiClonePointer(),
                                                                       FfiConverterString.lower(text), $0)
        })
    }

    open func synthesizeWithVoice(text: String, voiceIndex: UInt32) throws -> SynthesisResult {
        return try FfiConverterTypeSynthesisResult.lift(rustCallWithError(FfiConverterTypePocketTTSError.lift) {
            uniffi_pocket_tts_ios_fn_method_pocketttsengine_synthesize_with_voice(self.uniffiClonePointer(),
                                                                                  FfiConverterString.lower(text),
                                                                                  FfiConverterUInt32.lower(voiceIndex), $0)
        })
    }

    open func unload() { try! rustCall {
        uniffi_pocket_tts_ios_fn_method_pocketttsengine_unload(self.uniffiClonePointer(), $0)
    }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypePocketTTSEngine: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = PocketTtsEngine

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> PocketTtsEngine {
        return PocketTtsEngine(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: PocketTtsEngine) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PocketTtsEngine {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: PocketTtsEngine, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypePocketTTSEngine_lift(_ pointer: UnsafeMutableRawPointer) throws -> PocketTtsEngine {
    return try FfiConverterTypePocketTTSEngine.lift(pointer)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypePocketTTSEngine_lower(_ value: PocketTtsEngine) -> UnsafeMutableRawPointer {
    return FfiConverterTypePocketTTSEngine.lower(value)
}

public struct AudioChunk {
    public var audioData: Data
    public var sampleRate: UInt32
    public var isFinal: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(audioData: Data, sampleRate: UInt32, isFinal: Bool) {
        self.audioData = audioData
        self.sampleRate = sampleRate
        self.isFinal = isFinal
    }
}

extension AudioChunk: Equatable, Hashable {
    public static func == (lhs: AudioChunk, rhs: AudioChunk) -> Bool {
        if lhs.audioData != rhs.audioData {
            return false
        }
        if lhs.sampleRate != rhs.sampleRate {
            return false
        }
        if lhs.isFinal != rhs.isFinal {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(audioData)
        hasher.combine(sampleRate)
        hasher.combine(isFinal)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeAudioChunk: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AudioChunk {
        return
            try AudioChunk(
                audioData: FfiConverterData.read(from: &buf),
                sampleRate: FfiConverterUInt32.read(from: &buf),
                isFinal: FfiConverterBool.read(from: &buf)
            )
    }

    public static func write(_ value: AudioChunk, into buf: inout [UInt8]) {
        FfiConverterData.write(value.audioData, into: &buf)
        FfiConverterUInt32.write(value.sampleRate, into: &buf)
        FfiConverterBool.write(value.isFinal, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeAudioChunk_lift(_ buf: RustBuffer) throws -> AudioChunk {
    return try FfiConverterTypeAudioChunk.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeAudioChunk_lower(_ value: AudioChunk) -> RustBuffer {
    return FfiConverterTypeAudioChunk.lower(value)
}

public struct PocketVoiceInfo {
    public var index: UInt32
    public var name: String
    public var gender: String
    public var description: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(index: UInt32, name: String, gender: String, description: String) {
        self.index = index
        self.name = name
        self.gender = gender
        self.description = description
    }
}

extension PocketVoiceInfo: Equatable, Hashable {
    public static func == (lhs: PocketVoiceInfo, rhs: PocketVoiceInfo) -> Bool {
        if lhs.index != rhs.index {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.gender != rhs.gender {
            return false
        }
        if lhs.description != rhs.description {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(index)
        hasher.combine(name)
        hasher.combine(gender)
        hasher.combine(description)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypePocketVoiceInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PocketVoiceInfo {
        return
            try PocketVoiceInfo(
                index: FfiConverterUInt32.read(from: &buf),
                name: FfiConverterString.read(from: &buf),
                gender: FfiConverterString.read(from: &buf),
                description: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: PocketVoiceInfo, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.index, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.gender, into: &buf)
        FfiConverterString.write(value.description, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypePocketVoiceInfo_lift(_ buf: RustBuffer) throws -> PocketVoiceInfo {
    return try FfiConverterTypePocketVoiceInfo.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypePocketVoiceInfo_lower(_ value: PocketVoiceInfo) -> RustBuffer {
    return FfiConverterTypePocketVoiceInfo.lower(value)
}

public struct SynthesisResult {
    public var audioData: Data
    public var sampleRate: UInt32
    public var channels: UInt32
    public var durationSeconds: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(audioData: Data, sampleRate: UInt32, channels: UInt32, durationSeconds: Double) {
        self.audioData = audioData
        self.sampleRate = sampleRate
        self.channels = channels
        self.durationSeconds = durationSeconds
    }
}

extension SynthesisResult: Equatable, Hashable {
    public static func == (lhs: SynthesisResult, rhs: SynthesisResult) -> Bool {
        if lhs.audioData != rhs.audioData {
            return false
        }
        if lhs.sampleRate != rhs.sampleRate {
            return false
        }
        if lhs.channels != rhs.channels {
            return false
        }
        if lhs.durationSeconds != rhs.durationSeconds {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(audioData)
        hasher.combine(sampleRate)
        hasher.combine(channels)
        hasher.combine(durationSeconds)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSynthesisResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SynthesisResult {
        return
            try SynthesisResult(
                audioData: FfiConverterData.read(from: &buf),
                sampleRate: FfiConverterUInt32.read(from: &buf),
                channels: FfiConverterUInt32.read(from: &buf),
                durationSeconds: FfiConverterDouble.read(from: &buf)
            )
    }

    public static func write(_ value: SynthesisResult, into buf: inout [UInt8]) {
        FfiConverterData.write(value.audioData, into: &buf)
        FfiConverterUInt32.write(value.sampleRate, into: &buf)
        FfiConverterUInt32.write(value.channels, into: &buf)
        FfiConverterDouble.write(value.durationSeconds, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSynthesisResult_lift(_ buf: RustBuffer) throws -> SynthesisResult {
    return try FfiConverterTypeSynthesisResult.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSynthesisResult_lower(_ value: SynthesisResult) -> RustBuffer {
    return FfiConverterTypeSynthesisResult.lower(value)
}

public struct TtsConfig {
    public var voiceIndex: UInt32
    public var temperature: Float
    public var topP: Float
    public var speed: Float
    public var consistencySteps: UInt32
    public var useFixedSeed: Bool
    public var seed: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(voiceIndex: UInt32, temperature: Float, topP: Float, speed: Float, consistencySteps: UInt32, useFixedSeed: Bool, seed: UInt32) {
        self.voiceIndex = voiceIndex
        self.temperature = temperature
        self.topP = topP
        self.speed = speed
        self.consistencySteps = consistencySteps
        self.useFixedSeed = useFixedSeed
        self.seed = seed
    }
}

extension TtsConfig: Equatable, Hashable {
    public static func == (lhs: TtsConfig, rhs: TtsConfig) -> Bool {
        if lhs.voiceIndex != rhs.voiceIndex {
            return false
        }
        if lhs.temperature != rhs.temperature {
            return false
        }
        if lhs.topP != rhs.topP {
            return false
        }
        if lhs.speed != rhs.speed {
            return false
        }
        if lhs.consistencySteps != rhs.consistencySteps {
            return false
        }
        if lhs.useFixedSeed != rhs.useFixedSeed {
            return false
        }
        if lhs.seed != rhs.seed {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(voiceIndex)
        hasher.combine(temperature)
        hasher.combine(topP)
        hasher.combine(speed)
        hasher.combine(consistencySteps)
        hasher.combine(useFixedSeed)
        hasher.combine(seed)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeTTSConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TtsConfig {
        return
            try TtsConfig(
                voiceIndex: FfiConverterUInt32.read(from: &buf),
                temperature: FfiConverterFloat.read(from: &buf),
                topP: FfiConverterFloat.read(from: &buf),
                speed: FfiConverterFloat.read(from: &buf),
                consistencySteps: FfiConverterUInt32.read(from: &buf),
                useFixedSeed: FfiConverterBool.read(from: &buf),
                seed: FfiConverterUInt32.read(from: &buf)
            )
    }

    public static func write(_ value: TtsConfig, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.voiceIndex, into: &buf)
        FfiConverterFloat.write(value.temperature, into: &buf)
        FfiConverterFloat.write(value.topP, into: &buf)
        FfiConverterFloat.write(value.speed, into: &buf)
        FfiConverterUInt32.write(value.consistencySteps, into: &buf)
        FfiConverterBool.write(value.useFixedSeed, into: &buf)
        FfiConverterUInt32.write(value.seed, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeTTSConfig_lift(_ buf: RustBuffer) throws -> TtsConfig {
    return try FfiConverterTypeTTSConfig.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeTTSConfig_lower(_ value: TtsConfig) -> RustBuffer {
    return FfiConverterTypeTTSConfig.lower(value)
}

public enum PocketTtsError {
    case ModelNotLoaded(message: String)

    case ModelLoadFailed(message: String)

    case TokenizationFailed(message: String)

    case InferenceFailed(message: String)

    case InvalidVoice(message: String)

    case InvalidConfig(message: String)

    case AudioEncodingFailed(message: String)

    case IoError(message: String)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypePocketTTSError: FfiConverterRustBuffer {
    typealias SwiftType = PocketTtsError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PocketTtsError {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .ModelNotLoaded(
                message: FfiConverterString.read(from: &buf)
            )

        case 2: return try .ModelLoadFailed(
                message: FfiConverterString.read(from: &buf)
            )

        case 3: return try .TokenizationFailed(
                message: FfiConverterString.read(from: &buf)
            )

        case 4: return try .InferenceFailed(
                message: FfiConverterString.read(from: &buf)
            )

        case 5: return try .InvalidVoice(
                message: FfiConverterString.read(from: &buf)
            )

        case 6: return try .InvalidConfig(
                message: FfiConverterString.read(from: &buf)
            )

        case 7: return try .AudioEncodingFailed(
                message: FfiConverterString.read(from: &buf)
            )

        case 8: return try .IoError(
                message: FfiConverterString.read(from: &buf)
            )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PocketTtsError, into buf: inout [UInt8]) {
        switch value {
        case .ModelNotLoaded(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(1))
        case .ModelLoadFailed(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(2))
        case .TokenizationFailed(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(3))
        case .InferenceFailed(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(4))
        case .InvalidVoice(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(5))
        case .InvalidConfig(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(6))
        case .AudioEncodingFailed(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(7))
        case .IoError(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(8))
        }
    }
}

extension PocketTtsError: Equatable, Hashable {}

extension PocketTtsError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

public protocol TtsEventHandler: AnyObject {
    func onAudioChunk(chunk: AudioChunk)

    func onProgress(progress: Float)

    func onComplete()

    func onError(message: String)
}

// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

// Put the implementation in a struct so we don't pollute the top-level namespace
private enum UniffiCallbackInterfaceTTSEventHandler {
    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    nonisolated(unsafe) static var vtable: UniffiVTableCallbackInterfaceTtsEventHandler = .init(
        onAudioChunk: { (
            uniffiHandle: UInt64,
            chunk: RustBuffer,
            _: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceTtsEventHandler.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.onAudioChunk(
                    chunk: FfiConverterTypeAudioChunk.lift(chunk)
                )
            }

            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onProgress: { (
            uniffiHandle: UInt64,
            progress: Float,
            _: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceTtsEventHandler.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.onProgress(
                    progress: FfiConverterFloat.lift(progress)
                )
            }

            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onComplete: { (
            uniffiHandle: UInt64,
            _: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceTtsEventHandler.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onComplete(
                )
            }

            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onError: { (
            uniffiHandle: UInt64,
            message: RustBuffer,
            _: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceTtsEventHandler.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.onError(
                    message: FfiConverterString.lift(message)
                )
            }

            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) in
            let result = try? FfiConverterCallbackInterfaceTtsEventHandler.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface TTSEventHandler: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitTTSEventHandler() {
    uniffi_pocket_tts_ios_fn_init_callback_vtable_ttseventhandler(&UniffiCallbackInterfaceTTSEventHandler.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private enum FfiConverterCallbackInterfaceTtsEventHandler {
    fileprivate nonisolated(unsafe) static var handleMap = UniffiHandleMap<TtsEventHandler>()
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceTtsEventHandler: FfiConverter {
    typealias SwiftType = TtsEventHandler
    typealias FfiType = UInt64

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypePocketVoiceInfo: FfiConverterRustBuffer {
    typealias SwiftType = [PocketVoiceInfo]

    static func write(_ value: [PocketVoiceInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePocketVoiceInfo.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PocketVoiceInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [PocketVoiceInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypePocketVoiceInfo.read(from: &buf))
        }
        return seq
    }
}

public func availableVoices() -> [PocketVoiceInfo] {
    return try! FfiConverterSequenceTypePocketVoiceInfo.lift(try! rustCall {
        uniffi_pocket_tts_ios_fn_func_available_voices($0
        )
    })
}

public func version() -> String {
    return try! FfiConverterString.lift(try! rustCall {
        uniffi_pocket_tts_ios_fn_func_version($0
        )
    })
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}

// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
nonisolated(unsafe) private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_pocket_tts_ios_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if uniffi_pocket_tts_ios_checksum_func_available_voices() != 18295 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_pocket_tts_ios_checksum_func_version() != 1067 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_pocket_tts_ios_checksum_method_pocketttsengine_cancel() != 21472 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_pocket_tts_ios_checksum_method_pocketttsengine_clear_reference_audio() != 15791 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_pocket_tts_ios_checksum_method_pocketttsengine_configure() != 6099 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_pocket_tts_ios_checksum_method_pocketttsengine_decode_latents() != 32770 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_pocket_tts_ios_checksum_method_pocketttsengine_get_config() != 11199 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_pocket_tts_ios_checksum_method_pocketttsengine_is_ready() != 13012 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_pocket_tts_ios_checksum_method_pocketttsengine_model_version() != 6641 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_pocket_tts_ios_checksum_method_pocketttsengine_parameter_count() != 2583 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_pocket_tts_ios_checksum_method_pocketttsengine_set_reference_audio() != 45329 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_pocket_tts_ios_checksum_method_pocketttsengine_start_true_streaming() != 40839 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_pocket_tts_ios_checksum_method_pocketttsengine_synthesize() != 33210 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_pocket_tts_ios_checksum_method_pocketttsengine_synthesize_with_voice() != 47071 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_pocket_tts_ios_checksum_method_pocketttsengine_unload() != 22828 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_pocket_tts_ios_checksum_constructor_pocketttsengine_new() != 13139 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_pocket_tts_ios_checksum_method_ttseventhandler_on_audio_chunk() != 19025 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_pocket_tts_ios_checksum_method_ttseventhandler_on_progress() != 5218 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_pocket_tts_ios_checksum_method_ttseventhandler_on_complete() != 36591 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_pocket_tts_ios_checksum_method_ttseventhandler_on_error() != 2521 {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitTTSEventHandler()
    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
